<?php
/**
 * Implements hook_menu().
 */
function dchess_menu() {
  $items['chess'] = array(
    'title' => 'Chess',
    'page callback' => 'dchess_board_render',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function dchess_permission() {
  return array(
    'administer dchess games' =>  array(
      'title' => t('Administer Chess Games'),
      'description' => t('Allows users to create/edit/delete chess games'),
    ),
    'view dchess games' => array(
      'title' => t('View Chess Games'),
      'description' => t('Allow users to participate in/view  a chess game.'),
    ),
  );
}

function dchess_board_render($game_key = NULL) {
  //Our dummy game data, let only user 2 and 3 play
  if(isset($game_key)) {
    $game = array(
      'w' => 2, 
      'b' => 3,
      'game_id' => $game_key
    );
    drupal_add_js(array('dchess' => drupal_json_encode($game)), array('type' => 'setting'));
  }

  drupal_add_library('dchess', 'chessjs');
  drupal_add_library('dchess', 'drupal_chess');
  drupal_add_css(drupal_get_path('module', 'dchess').'/dchess_board.css');
  $output = theme('dchess_board');
  return $output;
}

/**
 *  Implements hook_nodejs_handlers_info
 */
function dchess_nodejs_handlers_info() {
  return array(
    //drupal_get_path('module', 'dchess').'/dchess.client.js',
  );
}

/**
 * Implements hook_theme().
 */
function dchess_theme($existing, $type, $theme, $path) {
  return array(
    'dchess_board' => array(
      'template' => 'dchess_board',
    ),
  );
}

/**
 * Implements hook_library().
 */
function dchess_library() {
  $libraries['chessjs'] = array(
    'title' => 'chess.js',
    'website' => 'https://github.com/jhlywa/chess.js',
    'version' => '0.1',
    'js' => array(
      drupal_get_path('module', 'dchess') . '/chess.js/chess.js' => array(),
    ),
  );
  $libraries['drupal_chess'] = array(
    'title' => 'Drupal Chess.js',
    'version' => '0.1',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js' => array('external'),
      drupal_get_path('module', 'dchess') . '/scripts/dchess.service.js' => array(),
      drupal_get_path('module', 'dchess') . '/scripts/dchess.controllers.js' => array(),
      drupal_get_path('module', 'dchess') . '/scripts/dchess.client.js' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_preprocess_html().
 */
function dchess_preprocess_html(&$vars) {
  $vars['attributes_array']['data-ng-app'] = "dChess"; 
}
