<?php
/**
 * Implements hook_menu().
 */
function dchess_menu() {
  $items['chess'] = array(
    'title' => 'Chess',
    'page callback' => 'dchess_board_render',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function dchess_board_render($game_key = NULL) {
  drupal_add_css(drupal_get_path('module', 'dchess').'/dchess_board.css');
  drupal_add_library('dchess', 'chessjs');
  if(isset($game_key)) {
    drupal_add_js(array('dchess' => 'w:2,b:3'), array('type' => 'setting'));
  }
  $output = theme('dchess_board');
  return $output;
}

/**
 *  Implements hook_nodejs_handlers_info
 */
function dchess_nodejs_handlers_info() {
  return array(
    drupal_get_path('module', 'dchess').'/dchess.client.js',
  );
}

/**
 * Implements hook_theme().
 */
function dchess_theme($existing, $type, $theme, $path) {
  return array(
    'dchess_board' => array(
      'template' => 'dchess_board',
    ),
  );
}

/**
 * Implements hook_library().
 */
function dchess_library() {
  $libraries['chessjs'] = array(
    'title' => 'chess.js',
    'website' => 'https://github.com/jhlywa/chess.js',
    'version' => '0.1',
    'js' => array(
      drupal_get_path('module', 'dchess') . '/chess.js/chess.js' => array(),
    ),
  );
  return $libraries;
}
